# Generated by Django 4.1.5 on 2023-12-10 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('en_name', models.CharField(help_text='관심사명(en)', max_length=30, primary_key=True, serialize=False)),
                ('ko_name', models.CharField(help_text='관심사명(ko)', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UserInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.ForeignKey(blank=True, help_text='관심사', null=True, on_delete=django.db.models.deletion.CASCADE, to='interest.interest')),
                ('user', models.ForeignKey(blank=True, help_text='유저', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
