# Generated by Django 4.1.5 on 2023-12-10 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicfeed',
            name='interest',
        ),
        migrations.AddField(
            model_name='privatefeed',
            name='category',
            field=models.CharField(default='정치', help_text='기사 카테고리', max_length=50),
        ),
        migrations.AddField(
            model_name='publicfeed',
            name='category',
            field=models.CharField(default='정치', help_text='기사 카테고리', max_length=50),
        ),
    ]
