# Generated by Django 4.1.5 on 2023-12-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_remove_publicfeed_interest_privatefeed_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatefeed',
            name='comment',
            field=models.TextField(help_text='댓글여론요약', null=True),
        ),
        migrations.AlterField(
            model_name='privatefeed',
            name='imgURL',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='publicfeed',
            name='comment',
            field=models.TextField(help_text='댓글여론요약', null=True),
        ),
        migrations.AlterField(
            model_name='publicfeed',
            name='imgURL',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='image'),
        ),
    ]
