# Generated by Django 4.1.5 on 2023-12-03 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interest', '0001_initial'),
        ('feed', '0002_publicfeed'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicfeed',
            name='interest',
            field=models.ForeignKey(blank=True, help_text='관심사', null=True, on_delete=django.db.models.deletion.CASCADE, to='interest.interest'),
        ),
    ]
